### ISSUE TITLE
I can not use the package through npm install

### ISSUE THREAD

**Issue by samuelcecilio** [mongoosejs/mongoose-update-versioning#1]
Probably because there is no `index.js` file in the package

**Comment by vkarpov15** [comment]
D'oh. Fixed in https://github.com/mongoosejs/mongoose-update-versioning/commit/cd90c3f1af2e32308fd13f5b8bfee6f42b04b68f.

**Comment by vkarpov15** [comment]
Released 0.1.1 with fix
