### ISSUE TITLE
Add support for Mongoose 7

### ISSUE THREAD

**Issue by neilenns** [mongoosejs/mongoose-update-versioning#6]
npm install mongoose-update-versioning
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vatsim-plan-verifier-server@1.0.0
npm ERR! Found: mongoose@7.4.2
npm ERR! node_modules/mongoose
npm ERR!   mongoose@"^7.3.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer mongoose@"5.x || 6.x" from mongoose-update-versioning@0.2.0
npm ERR! node_modules/mongoose-update-versioning
npm ERR!   mongoose-update-versioning@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\neile\AppData\Local\npm-cache\_logs\2023-08-08T15_22_37_553Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\neile\AppData\Local\npm-cache\_logs\2023-08-08T15_22_37_553Z-debug-0.log

**Comment by vkarpov15** [comment]
Just shipped v0.3.0 with the fix.
